MemoryGame/Models/CardDetails.cs
namespace MemoryGame.Models{
    public class CardDetails
    {
        public int CardID { get; set; }
        public int GameID { get; set; }
        public string? CardPosition { get; set; }
        public string? CardValue { get; set; }
        public bool IsMatched { get; set; }

		// test
	

    }
}

MemoryGame/Models/ErrorViewModel.cs
namespace MemoryGame.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}



MemoryGame/Models/GameDetails.cs
using System;
using System.Collections.Generic;

namespace MemoryGame.Models
{
    
    public class GameDetails
    {
        public int GameID { get; set; }
        public int Player1 { get; set; }
        public int Player2 { get; set; }
        public string? GameStatus { get; set; }
        public DateTime? StartTime { get; set; }
        public DateTime? EndTime { get; set; }

    }
}

MemoryGame/Models/GameViewModel.cs
using System.Collections.Generic;

namespace MemoryGame.Models
{
    public class GameViewModel
    {
        public Game Game { get; set; }
        public List<Card> Cards { get; set; } 
    }
} 

MemoryGame/Models/MoveDetails.cs
namespace MemoryGame.Models{
public class MoveDetails
    {
        public int MoveID { get; set; }
        public int GameID { get; set; }
        public int PlayerID { get; set; }
        public int FirstCardID { get; set; }
        public int SecondCardID { get; set; }
        public bool IsMatch { get; set; }
        public DateTime MoveTime { get; set; }

    }
}

MemoryGame/Models/PlayerDetails.cs
namespace MemoryGame.Models
{
    public class PlayerDetails
    {
        public int PlayerID { get; set; }
        public string? PlayerName { get; set; }
        public string? PlayerUsername { get; set; }
        public string? Password { get; set; }

    }
}

MemoryGame/Models/PlayerMethods.cs
/*using MemoryGame.Models;
using System.Data;
using Microsoft.Data.SqlClient;

namespace MemoryGame.Models{
    public class PlayerMethods{
        public PlayerMethods(){}
        public int InsertPlayer(PlayerDetails playerDetails, out string errormsg){
            
            String ConnectionString = "Server=localhost,1433; Database=MemoryGameDB; User Id=sa; Password=Luddis003; Encrypt=False; TrustServerCertificate=True;";
            String sqlstring = "INSERT INTO Players (PlayerName, PlayerUsername, PasswordHash) VALUES (@PlayerName, @PlayerUsername, @PasswordHash);";
            
            using SqlConnection sqlConnection = new SqlConnection(ConnectionString);
            using SqlCommand sqlCommand = new SqlCommand(sqlstring, sqlConnection);
            {
                sqlCommand.Parameters.AddWithValue("@PlayerName", playerDetails.PlayerName);
                sqlCommand.Parameters.AddWithValue("@PlayerUsername", playerDetails.PlayerUsername);
                sqlCommand.Parameters.AddWithValue("@PasswordHash", playerDetails.PasswordHash);
                

                try
                {
                    sqlConnection.Open();
                    Console.WriteLine("Connection successful.");
                    int i = 0;
                    i = sqlCommand.ExecuteNonQuery();
                    if (i == 1) { errormsg = ""; }
                    else { errormsg = "insert failed"; }
                    return i;

                }
                catch (Exception e)
                {
                    errormsg = e.Message;
                    return 0;
                }
                finally
                {
                    sqlConnection.Close();

                }
            }
        }
        public int GetPlayer(PlayerDetails playerDetails, out string errormsg){
            String ConnectionString = "Server=localhost,1433; Database=MemoryGameDB; User Id=sa; Password=Luddis003; Encrypt=False; TrustServerCertificate=True;";
            String sqlstring = "SELECT FROM Players WHERE PlayerUsername = @PlayerUsername;";
            
            using SqlConnection sqlConnection = new SqlConnection(ConnectionString);
            using SqlCommand sqlCommand = new SqlCommand(sqlstring, sqlConnection);
            {
                
                try
                {
                    sqlConnection.Open();
                    Console.WriteLine("Connection successful.");
                    GameDetails.Player1 = PlayerDetails.PlayerID;
                    int i = 0;
                    i = sqlCommand.ExecuteNonQuery();
                    if (i == 1) { errormsg = ""; }
                    else { errormsg = "insert failed"; }
                    return i;

                }
                catch (Exception e)
                {
                    errormsg = e.Message;
                    return 0;
                }
                finally
                {
                    sqlConnection.Close();

                }
            }
        
        }
    }
} */

MemoryGame/Controllers/GameController.cs
using Microsoft.AspNetCore.Mvc;
// using MemoryGame.Data;
using MemoryGame.Models;
//using Microsoft.Data.SqlClient;
using System.Linq;

namespace MemoryGame.Controllers
{
    public class GameController : Controller
    {
        public IActionResult CreateGame(){
            return View();
        }
        public IActionResult JoinGame(){
            return View();
        }
        public IActionResult Login(){
            return View();
        }
        public IActionResult Logout(){
            return View();
        }
        public IActionResult Play(){
            return View();
        }
    }
        
}

MemoryGame/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MemoryGame.Models;

namespace MemoryGame.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

MemoryGame/Views/Game/Login.cshtml
@model MemoryGame.Models.PlayerDetails

<h1>Log in to play</h1>
<form asp-action="Login">
	<label>Username:</label> </br>
	<input asp-for="PlayerUsername" type="text"/>
	</br>
	</br>
	<label>Password:</label> </br>
	<input asp-for="Password" type="password"/>
	</br>
	</br>
	<input type="submit" value="Log in">
</form>

MemoryGame/Views/Game/Play.cshtml
@model MemoryGame.Models.GameViewModel

<div class="container">
    <h1>Memory Game</h1>
    <div class="row">
        @foreach (var card in Model.Cards)
        {
            <div class="col-3">
                <form asp-action="MakeMove" method="post">
                    <input type="hidden" name="gameId" value="@Model.Game.GameID" />
                    <input type="hidden" name="cardPosition" value="@card.CardPosition" />
                    <button type="submit" class="btn btn-primary">
                        @if (card.IsMatched)
                        {
                            <span>@card.CardValue</span>
                        }
                        else
                        {
                            <span>?</span>
                        }
                    </button>
                </form>
            </div>
        }
    </div>
</div>

MemoryGame/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to the Memory Game!</h1>
    <p>Choose an option to get started:</p>
    <a class="btn btn-primary btn-lg" href="/Game/Start">Start a New Game</a>
</div>

MemoryGame/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MemoryGame</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MemoryGame.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MemoryGame</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Game" asp-action="CreateGame">CreateGame</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Game" asp-action="JoinGame">JoinGame</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Game" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Game" asp-action="Logout">Logout</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Game" asp-action="Play">Play</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - MemoryGame - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>